config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
        sessions: 'employees/sessions'
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#home"
  resources :employees
  resources :departments
  resources :leaves
  resources :holidays
end

app/models/holiday.rb
class Holiday < ApplicationRecord
end

app/controllers/holidays_controller.rb
class HolidaysController < ApplicationController
  before_action :authenticate_employee!
  before_action :find_holiday, except: [:new, :create, :index]

  def index
    @holidays = Holiday.all
  end

  def new
    @holiday = Holiday.new
  end

  def create
    @holiday = Holiday.new(holiday_params)

    if @holiday.save
      redirect_to @holiday
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    unless @holiday.update(holiday_params)
      render 'edit'
    else
      redirect_to @holiday
    end
  end

  def show
    
  end

  def destroy
    @holiday.destroy
    redirect_to holidays_path
  end

  private

  def holiday_params
    params.require(:holiday).permit(:date, :occasion, :day)
  end

  def find_holiday
    @holiday = Holiday.find(params[:id])
  end
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/views/holidays/_form.html.erb
<%= form_with model: @holiday do |form| %>
  <div class="form-field">
    <%= form.label :date %>
    <%= form.date_field :date, class: 'form-control' %>
  </div><br>

  <div class="form-field">
    <%= form.label :occasion %>
    <%= form.text_field :occasion, class: 'form-control' %>
  </div><br>

  <div class="form-field">
    <%= form.label :day %>
    <%= form.text_field :day, class: 'form-control' %>
  </div><br>

  <div class="form-field">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          <h5>Edit Holiday</h5>
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/holidays/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header", style="background-color: #D5F5E3;">
          <strong><h4>Holiday Calender</h4></strong>
        </div>
        <div class="card-body">
          <p class="card-text">
            
        <table class="table table-light table-striped table-hover">
          <thead class="thead-dark">
            <tr>
              <th>Date</th>
              <th>Occasion</th>
              <th>Day</th>
              <% if current_employee.role == 'admin' %>
              <th colspan="3">Actions</th>
              <% end %> 
            </tr>
          </thead>
          <tbody>
            <% @holidays.each do |holiday| %>
            <tr>
              <td><%= holiday.date.strftime("%d %b, %Y") %></td>
              <td><%= holiday.occasion %></td>
              <td><%= holiday.day %></td>
              <% if current_employee.role == 'admin' %>
                <td><%= link_to 'Edit', edit_holiday_path(holiday), class: 'btn btn-outline-success btn-sm' %></td>
                <td><%= link_to 'Destroy', holiday, data: { "turbo_method": :delete , turbo_confirm: "Are you sure?"}, class: 'btn btn-outline-danger btn-sm'  %></td>
                <% end %>
            </tr>
            <% end %>
          </tbody>
        </table>
            </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/holidays/new.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Add Holiday
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>