config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
        sessions: 'employees/sessions'
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#home"
  resources :employees
  resources :departments
  resources :leaves
  resources :holidays
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :department
  has_many :leaves, class_name: "Leave", dependent: :destroy

  enum gender: { female: "female", male: "male" }

  enum role: [:employee, :admin]

  validates :name, :email, :phone_number, presence: true
  validates :phone_number, length: { is: 10 }, numericality: { only_integer: true }
  validates_each :name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

    def self.ransackable_attributes(auth_object = nil)
    ["address", "created_at", "date_of_joining", "department_id", "designation", "dob", "email", "gender", "id", "name", "phone_number", "role", "updated_at"]
    end
    def self.ransackable_associations(auth_object = nil)
      ["department", "leaves"]
    end
end

app/controllers/employees/confirmations_controller.rb
# frozen_string_literal: true

class Employees::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/employees/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Employees::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/employees/passwords_controller.rb
# frozen_string_literal: true

class Employees::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/employees/registrations_controller.rb
# frozen_string_literal: true

class Employees::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees/sessions_controller.rb
# frozen_string_literal: true

class Employees::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/employees/unlocks_controller.rb
# frozen_string_literal: true

class Employees::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: %i(show update edit destroy)

  def index
    @q = Employee.ransack(params[:q])
    @employees = @q.result(distinct: true)
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      redirect_to @employee
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @employee.update(employee_params)
      redirect_to @employee
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path
  end

  private

  def employee_params
    params.require(:employee).permit(:name, :email, :address, :gender, :dob, :phone_number, :designation, :date_of_joining, :department_id)
  end

  def find_employee
    @employee = Employee.find(params[:id])
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with model: @employee do |form| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@employee.errors.count, "error") %> prohibited
        this seed from being saved:
      </h3>
      <ul>
        <% @employee.errors.full_messages.each do |msg| %>
          <li style="color: red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.text_field :email, class: 'form-control'  %>
  </div>

  <div class="form-group">
    <%= form.label :address %><br>
    <%= form.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :gender %><br>
    <%= form.text_field :gender, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :dob %><br>
    <%= form.date_field :dob, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number %><br>
    <%= form.text_field :phone_number, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :designation %><br>
    <%= form.text_field :designation, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_joining %><br>
    <%= form.date_field :date_of_joining, class: 'form-control' %>
  </div>

   <div class="form-group">
    <%= form.label :department %><br />
    <%= form.collection_select :department_id,  Department.all,  :id, :name %>
  </div>
<br>
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/employees/edit.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Update Employee
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/home.html.erb
	<% if employee_signed_in? %>
    <div class="alert alert-warning alert-dismissible fade show">
        <p>Hello, <%=current_employee.name %>!</p>
        <p>You are logged in as <%=current_employee.role %></p>

    <p>You have been successfully authenticated!</p>
    <p>You are now ready to interact with this application.</p>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
    </div>
</div>
    <% else %>
      <p>Please Sign Up or login!</p>
      <%=link_to 'Sign Up', new_employee_registration_path, class: 'btn btn-outline-primary' %>
      <%=link_to 'Login', new_employee_session_path, class: 'btn btn-outline-primary' %>
    <% end %>
  

app/views/employees/index.html.erb
<% if employee_signed_in? && current_employee.role == 'admin' %>
<div class="container-fluid mt-3">
  <div class="row">
    <div>
      <%= search_form_for @q, remote: true do |f| %>
      <%= f.search_field :name_cont, placeholder: 'Search Here', class: 'form-control search-right' %>
    </div>
    <div>
      <%= f.submit class: 'btn btn-outline-secondary search-button' %>
      <% end %>
    </div>
  </div>
</div>

<br>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <h1>Employees List</h1>

<div class="right">
  <%= link_to 'Add Employee', new_employee_path, class: 'btn btn-outline-primary' %>
</div>
<br><br>
    <table class="table table-light table-striped table-hover">
      <thead>
        <tr>
          <th scope="col"><%= sort_link(@q, :name) %></th>
          <th scope="col"><%= sort_link(@q, :email) %></th>
          <th scope="col"><%= sort_link(@q, :address) %></th>
          <th scope="col"><%= sort_link(@q, :gender) %></th>
          <th scope="col"><%= sort_link(@q, :dob) %></th>
          <th scope="col"><%= sort_link(@q, :phone_number) %></th>
          <th scope="col"><%= sort_link(@q, :designation) %></th>
          <th scope="col"><%= sort_link(@q, :date_of_joining) %></th>
          <th scope="col"><%= sort_link(@q, :department) %></th>
          <th scope="col"colspan="3">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @employees.each do |employee| %>
        <tr>
          <td><%= employee.name %></td>
          <td><%= employee.email %></td>
          <td><%= employee.address %></td>
          <td><%= employee.gender %></td>
          <td><%= employee.dob %></td>
          <td><%= employee.phone_number %></td>
          <td><%= employee.designation %></td>
          <td><%= employee.date_of_joining %></td>
          <td><%= employee.department&.name %></td>
          <td><%= link_to 'Show', employee, class: 'btn btn-outline-primary btn-sm' %></td>
            <td><%= link_to 'Edit', edit_employee_path(employee), class: 'btn btn-outline-success btn-sm' %></td>
            <td><%= link_to 'Destroy', employee, data: { "turbo_method": :delete , turbo_confirm: "Are you sure?"}, class: 'btn btn-outline-danger btn-sm'  %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>
<% else %>
<div class="alert alert-danger alert-dismissible fade show" role="alert">
  <strong>You are not authorised to access this page!!</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>

app/views/employees/new.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Add Employee
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/show.html.erb
<div class="container mt-3">
  <div class="mt-4 p-5 bg-light text-dark rounded">
    <h3>Employee Profile</h3> 
    <p>
      <table class="table table-light table-striped table-hover">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Address</th>
            <th>Gender</th>
            <th>Date of Birth</th>
            <th>Phone Number</th>
            <th>Designation</th>
            <th>Date of Joining</th>
            <th>Department</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @employee.name %></td>
            <td><%= @employee.email %></td>
            <td><%= @employee.address %></td>
            <td><%= @employee.gender %></td>
            <td><%= @employee.dob %></td>
            <td><%= @employee.phone_number %></td>
            <td><%= @employee.designation %></td>
            <td><%= @employee.date_of_joining %></td>
            <td><%= @employee.department&.name %></td>
          </tr>
        </tbody>
      </table>
      <div class="text-center">
        <%= link_to 'Edit', edit_employee_path(@employee), class: 'btn btn-outline-success' %>
        <%= link_to 'Back', employees_path, class: 'btn btn-outline-dark' %>
      </div>
    </p> 
  </div>
</div>