config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
        sessions: 'employees/sessions'
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#home"
  resources :employees
  resources :departments
  resources :leaves
  resources :holidays
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :employees

  validates :name, presence: true
  validates_each :name do |record, attr, value|
    record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :find_department, only: %i(show update edit destroy)

  def index
    @q = Department.ransack(params[:q])
    @departments = @q.result(distinct: true)
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new(department_params)

    if @department.save
      redirect_to @department
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @department.update(department_params)
      redirect_to @department
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @department.destroy
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit(:name)
  end

  def find_department
    @department = Department.find(params[:id])
  end
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/views/departments/_form.html.erb
<%= form_with model: @department do |form| %>
  <% if @department.errors.any? %>
    <div id="error_explanation">
      <h3>
        <%= pluralize(@department.errors.count, "error") %> prohibited
        this seed from being saved:
      </h3>
      <ul>
        <% @department.errors.full_messages.each do |msg| %>
          <li style="color: red;"><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
	<div>
		<%= form.label :name %><br>
    <%= form.text_field :name, class: 'form-control' %>
	</div>
	<br>
  <div>
    <%= form.submit class: 'btn btn-primary btn-sm' %>
  </div>

<% end %>

app/views/departments/edit.html.erb
<div class="container mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Update Department
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/departments/index.html.erb
<div class="container-fluid mt-3">
  <div class="row d-flex justify-content-center">
    <div class="col-md-12">
      <h1>Departments List</h1>
    <div class="right">
      <%= link_to 'Add Department', new_department_path, class: 'btn btn-outline-primary' %>
    </div>
    <br><br>

    <table class="table table-light table-striped table-hover">
      <thead>
        <tr>
          <th><%=sort_link(@q, :name)%></th>
          <% if current_employee.role == 'admin' %>
          <th colspan="3">Actions</th>
          <% end %> 
        </tr>
      </thead>
      <tbody>
        <% @departments.each do |department| %>
        <tr>
          <td><%= department.name %></td>
          <% if current_employee.role == 'admin' %>
            <td><%= link_to 'Show', department, class: 'btn btn-outline-primary btn-sm'%></td>
            <td><%= link_to 'Edit', edit_department_path(department), class: 'btn btn-outline-success btn-sm' %></td>
            <td><%= link_to 'Destroy', department, data: { "turbo_method": :delete , turbo_confirm: "Are you sure?"}, class: 'btn btn-outline-danger btn-sm'  %></td>
            <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/departments/new.html.erb
<div class="container mt-3">
  <div class="row">
    <div class="col-md-8">
      <div class="card">
        <div class="card-header">
          Add Department
        </div>
        <div class="card-body">
          <p class="card-text"><%= render 'form' %></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/departments/show.html.erb
<div class="container mt-3">
  <div class="mt-4 p-5 bg-light text-dark rounded">
    <h3>Department Detail</h3> 
    <p>
    <table class="table table-light table-striped table-hover">
    	<thead>
    		<tr>
    			<th>Name</th>
    		</tr>
    	</thead>
      <tbody>
        <tr>
          <td><%= @department.name %></td>
        </tr>
      </tbody>
    </table>
    <div class="text-center">
      <%= link_to 'Edit', edit_department_path(@department), class: 'btn btn-outline-success' %>
      <%= link_to 'Back', departments_path, class: 'btn btn-outline-dark' %>
    </div>
  </p>
  </div>
</div>