config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, controllers: {
        sessions: 'employees/sessions'
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "employees#home"
  resources :employees
  resources :departments
  resources :leaves
  resources :holidays
end

app/views/layouts/navbar/_header.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Employee Management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if employee_signed_in? && current_employee.role == 'admin' %>
          <%= link_to 'Employees', employees_path, class: 'nav-link' %>
        </li>
        <% end %>
        <li class="nav-item">
          <%= link_to 'Departments', departments_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Employee Leaves', leaves_path, class: 'nav-link' %>
        </li>
        <% if employee_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Holidays', holidays_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign out', destroy_employee_session_path, data: { turbo_method: :delete } , class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign Up', new_employee_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign In', new_employee_session_path, class: 'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>